version: "3.9"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8085:8989
    environment:
      - PUID=1026
      - PGID=65536
      - TZ="Europe/Rome"
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/plexMedia:/plexMedia
      - /volume1/downloads:/downloads
    restart: unless-stopped
#     networks:
#       - default
# networks:
#   default:
#     external: 
#       name: bridge