version: "3.9"
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    ports:
      - 8086:8181
    environment:
      - PUID=1026
      - PGID=65536
      - TZ="Europe/Rome"
    volumes:
      - /volume1/docker/tautulli/config:/config
    restart: unless-stopped
#     networks:
#       - default
# networks:
#   default:
#     external: 
#       name: bridge