version: "3.9"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    ports:
      - 8083:7977
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1026
      - PGID=65536
      - TZ=Europe/Rome
      - WEBUI_PORT=8083
    volumes:
      - /volume1/docker/qbittorrent/config:/config
      - /volume1/downloads:/downloads
      - /volume1/plexMedia:/plexMedia
    restart: unless-stopped
#     networks:
#       - default
# networks:
#   default:
#     external: 
#       name: bridge