version: "3.9"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      - PUID=1026
      - PGID=65536
      - TZ=Europe/Rome
    ports:
      - 8080:80
      - 8081:443
    volumes:
      - /volume1/docker/heimdall/config:/config
    restart: unless-stopped
#     networks:
#       - default
# networks:
#   default:
#     external: 
#       name: bridge
