version: "3.9"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
    #   - "67:67/udp"
    #   - "7080:80/tcp"
    environment:
      TZ: 'Europe/Rome'
      WEBPASSWORD: 'pihole@Home'
      WEB_PORT: 8888
      TEMPERATUREUNIT: 'c'
      DNSMASQ_LISTENING: local
      ServerIP: '10.0.0.252'
    # Volumes store your data between container upgrades
    volumes:
      - '/volume1/docker/pihole/etc-pihole/:/etc/pihole/'
      - '/volume1/docker/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 127.0.0.1
      - 1.1.1.2
      - 1.0.0.2
