version: "3.9"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: Radarr
    ports:
     - 8084:7878
    environment:
      - PUID=1026
      - PGID=65536
      - TZ="Europe/Rome"
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/plexMedia:/plexMedia
      - /volume1/downloads:/downloads
    restart: unless-stopped
#     networks:
#       - default
# networks:
#   default:
#     external: 
#       name: bridge